name: caesar_cipher_mobile
description: A modern Flutter security suite for Caesar and AES encryption.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  encrypt: ^5.0.3
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
